[colors.primary]
background = "#181818"
foreground = "#ffffff"

[window]
opacity = 0.7

[env]
WINIT_X11_SCALE_FACTOR = "1.2"

[font]
size = 12.0

[font.normal]
family = "Terminus"
style = "Bold"

[terminal]

[terminal.shell]
args = ["-c", "neofetch && exec zsh"]
program = "/usr/bin/zsh"
